//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_de_consulta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_clinicaEntities_ : DbContext
    {
        public bd_clinicaEntities_()
            : base("name=bd_clinicaEntities_")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<citas> citas { get; set; }
        public DbSet<historial_clinico> historial_clinico { get; set; }
        public DbSet<horarios> horarios { get; set; }
        public DbSet<medicamentos> medicamentos { get; set; }
        public DbSet<medicamentos_historia> medicamentos_historia { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<servicio_historia> servicio_historia { get; set; }
        public DbSet<servicios> servicios { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
