//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_de_consulta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_clinico
    {
        public historial_clinico()
        {
            this.medicamentos_historia = new HashSet<medicamentos_historia>();
            this.servicio_historia = new HashSet<servicio_historia>();
        }
    
        public int id { get; set; }
        public int cedula_paciente { get; set; }
        public string antecedentes_familiares { get; set; }
        public string antecedentes_personales { get; set; }
        public string cirugias { get; set; }
        public string enfermedades_cronicas { get; set; }
        public string fecha_novedad { get; set; }
        public string motivo_consulta { get; set; }
        public string diagnostico { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        public virtual ICollection<medicamentos_historia> medicamentos_historia { get; set; }
        public virtual ICollection<servicio_historia> servicio_historia { get; set; }
    }
}
