//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_de_consulta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historial_clinico
    {
        public int id { get; set; }
        public Nullable<int> cedula_paciente { get; set; }
        public string antecedentes_familiares { get; set; }
        public string antecedentes_personales { get; set; }
        public string cirugias { get; set; }
        public string alergias { get; set; }
        public string enfermedades_cronicas { get; set; }
        public string fecha_novedad { get; set; }
    }
}
