//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_de_consulta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicios
    {
        public servicios()
        {
            this.servicio_historia = new HashSet<servicio_historia>();
        }
    
        public string codigo_servicio { get; set; }
        public string nombre_servicio { get; set; }
        public Nullable<int> valor_costo_servicio { get; set; }
        public Nullable<int> valor_venta_servicio { get; set; }
    
        public virtual ICollection<servicio_historia> servicio_historia { get; set; }
    }
}
