//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gestion_de_consulta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id { get; set; }
        public Nullable<int> cedula { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string clave { get; set; }
        public string telefono { get; set; }
        public Nullable<int> id_rol { get; set; }
        public string correo { get; set; }
    }
}
